host: 0.0.0.0
port: 5832

name: OJ

database:
  uri: default:///sqlite
  max_json_length: 2000

frontend:
  thirdparty_host: https://cdn.jsdelivr.net/gh/y3oj/static-files-host
  # thirdparty_host: https://raw.githubusercontent.com/y3oj/static-files-host/main