host: 0.0.0.0
port: 5832
secret_key: secret_key

name: OJ

database:
  uri: default:///sqlite
  limit:
    json: 10000
    code: 10000
    link: 200
    details: 10000

user:
  limit:
    summary: 40
    description: 1000

problem:
  defaults:
    time_limit: 1000
    memory_limit: 128
    judge: 'testlib-multi'

frontend:
  thirdparty_host: https://cdn.jsdelivr.net/gh/y3oj/static-files-host
  # thirdparty_host: https://raw.githubusercontent.com/y3oj/static-files-host/main
 
template:
  logo: /demo/logo.png

judger:
  port: 5834
  remote_host: localhost
  sandbox_rootfs: ./sandbox-rootfs/root.x86_64
